DROP TABLE savings CASCADE CONSTRAINTS;
DROP TABLE expenses CASCADE CONSTRAINTS;
DROP TABLE budgets CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  email VARCHAR2(100) UNIQUE NOT NULL,
  password_hash VARCHAR2(255) NOT NULL
);

CREATE TABLE budgets (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  category VARCHAR2(50),
  monthly_limit NUMBER(10,2)
);

CREATE TABLE expenses (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  category VARCHAR2(50),
  amount NUMBER(10,2),
  description VARCHAR2(255),
  expense_date DATE
);

CREATE TABLE savings (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  goal_name VARCHAR2(50),
  target_amount NUMBER(10,2),
  current_amount NUMBER(10,2)
);

INSERT INTO users (username, email, password_hash)
VALUES ('ishan', 'ishan@example.com', 'hashedpassword');

INSERT INTO budgets (user_id, category, monthly_limit)
VALUES (1, 'Food', 300.00);

INSERT INTO budgets (user_id, category, monthly_limit)
VALUES (1, 'Transport', 150.00);

INSERT INTO expenses (user_id, category, amount, description, expense_date)
VALUES (1, 'Food', 50.00, 'Lunch', SYSDATE);

INSERT INTO expenses (user_id, category, amount, description, expense_date)
VALUES (1, 'Transport', 20.00, 'Bus fare', SYSDATE);

INSERT INTO savings (user_id, goal_name, target_amount, current_amount)
VALUES (1, 'Laptop', 1000.00, 200.00);

COMMIT;